name: Restrict String Push

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  restrict_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for restricted string
        run: |
          if grep -q "vivek-nikita" ${GITHUB_WORKSPACE}/*; then
            echo "Error: Restricted string found"
            exit 1
          fi